### ISSUE TITLE
Assertion error using document.all in v0.2.1

### ISSUE THREAD

**Issue by Lavton** [alvinwan/TexSoup#100]
Hello!
I'm trying to use
```document = TexSoup(open(filename)).document```
and then
```[str(a) for a in document.all]```
The generator on the second line after few interactions raise the AssertionError (from TexSoup/data.py:113, assert isinstance(child, TexExpr)). The previous version 0.2.0 doesn't fall on this example

**Comment by alvinwan** [comment]
@Lavton Thanks for reporting! Can you provide a short reproducible script? i.e., with latex that causes this, no longer than a few lines
