### ISSUE TITLE
Error while using print(list(soup.find_all('section')))

### ISSUE THREAD

**Issue by NishealJ** [alvinwan/TexSoup#101]
This happens when there is an extra {} or [] in the latex file, also if the latex file is not systematically correct.

Traceback (most recent call last):
  File "some.py", line 5, in <module>
    soup = TexSoup(text)
  File "/usr/local/lib/python3.7/site-packages/TexSoup/__init__.py", line 84, in TexSoup
    parsed, src = read(tex_code, skip_envs=skip_envs)
  File "/usr/local/lib/python3.7/site-packages/TexSoup/tex.py", line 19, in read
    content = read_tex(buf, skip_envs=skip_envs)
  File "/usr/local/lib/python3.7/site-packages/TexSoup/reader.py", line 262, in read_tex
    expr.args = read_args(src, expr.args)
  File "/usr/local/lib/python3.7/site-packages/TexSoup/reader.py", line 398, in read_args
    tex_text = read_tex(src)
  File "/usr/local/lib/python3.7/site-packages/TexSoup/reader.py", line 268, in read_tex
    return read_arg(src, c)
  File "/usr/local/lib/python3.7/site-packages/TexSoup/reader.py", line 424, in read_arg
    return Arg.parse(content)
  File "/usr/local/lib/python3.7/site-packages/TexSoup/data.py", line 981, in parse
    ' mistyped closing punctuation, misalignment.' % (str(s)))
TypeError: Malformed argument. First and last elements must match a valid argument format. In this case, TexSoup could not find matching punctuation for: ['{', '%', '\n   ', TexCmd('list', [RArg(), RArg('%', '\n     ', TexCmd('leftmargin1'), '.5cm  ', '%%% ADJUST QUOTE MARGINS %%%', '\n     ', TexCmd('rightmargin1'), '.5cm  ', '%%% ADJUST QUOTE MARGINS %%%', '\n   ')]), '\n   ', TexCmd('item'), TexCmd('onecolumn'), '\n\n', TexCmd('title', [RArg(TexCmd('textbf', [RArg('Article Title')]))]), ' ', '%%% TITLE %%%', '\n', TexCmd('author', [RArg('Name \\\\ ', '%%% AUTHOR %%%', '\n\t', TexCmd('textit', [RArg('University')]))]), ' ', '%%% UNIVERSITY %%%', '\n', TexCmd('date', [RArg()]), '\n\n\n', TexCmd('pagestyle', [RArg('fancy')]), '\n', TexCmd('fancyhf', [RArg()]), '\n', TexCmd('fancyhead', [RArg()]), '\n', TexCmd('fancyfoot', [OArg('RE,LO'), RArg(TexCmd('textit', [RArg('Cuneiform Digital Library Journal year:number')]))]), ' ', '%%% YEAR:NUMBER %%%', '\n', TexCmd('fancyfoot', [OArg('LE,RO'), RArg('page~', TexCmd('thepage'), '~of~', TexCmd('pageref', [RArg('LastPage')]))]), '\n', TexCmd('fancyfoot', [OArg('C'), RArg()]), '\n', TexCmd('renewcommand', [RArg(TexCmd('headrulewidth')), RArg('0pt')]), '\n', TexCmd('renewcommand', [RArg(TexCmd('footrulewidth')), RArg('0pt')]), '\n\n\n', TexEnv('document'), '\n\n\n', '\n'].
Common issues include: Unescaped special characters, mistyped closing punctuation, misalignment.

**Comment by NishealJ** [comment]
Hi @alvinwan can you please take alook?

**Comment by alvinwan** [comment]
@NishealJ can you provide a short reproducible script? e.g., with the latex that produced this. should be no longer than a few lines

**Comment by alvinwan** [comment]
(Closing due to lack of response. Feel free to reopen)
