### ISSUE TITLE
Parsing the content of math environments?

### ISSUE THREAD

**Issue by jonathan-laurent** [alvinwan/TexSoup#106]
Currently, it seems to me that TexSoup treats the content of a math environment  ($...$, \(...) or \[...\]) like a single token.
Is there any way to get a structured representation of this content too? I was thinking of getting a string representation of the inside of $...$ and then calling TexSoup on it recursively but I am not sure this would work.

To be even more concrete, here is an example of a task I am interested in performing:

- Find all instances of `\infer{A}{B}` within a math environment and replace it by `\infer{B}{A}` where A and B could be arbitrary Latex code.

Could one use TexSoup to do this?

**Comment by alvinwan** [comment]
@jonathan-laurent Thanks for creating this issue! I've just made a change that will allow this. The linked PR will have a passing test for this math env replacement, reproduced below:

```
    soup = TexSoup(r'$$\infer{A}{B}\infer{C}{D}$$')
    assert soup.infer is not None, repr(soup.expr)
    for infer in soup.find_all('infer'):
        infer.args = infer.args[::-1]
    assert str(soup) == r'$$\infer{B}{A}\infer{D}{C}$$'
```

**Comment by qwenger** [comment]
Wow, that's exactly the issue I was searching for.

Thank you very much @alvinwan for this really handy library! Would you consider pushing a release to PyPI for this new math parsing feature?

**Comment by jonathan-laurent** [comment]
I just tried it and it works great. Thanks!

**Comment by alvinwan** [comment]
@qwenger yup, just pushed! https://pypi.org/project/TexSoup/0.3.1/
