### ISSUE TITLE
Question regarding conversion

### ISSUE THREAD

**Issue by nivaca** [alvinwan/TexSoup#109]
Hi, I've been testing TexSoup for processing TeX files.
I have a question: if I make changes to a soup tree, how can I output again a TeX file? Is that possible?
Thanks!

**Comment by alvinwan** [comment]
@nivaca Yep, you can. Just call `str(...)` on the soup object to obtain the modified latex.

Here are some examples: https://texsoup.alvinwan.com/docs/soup.html#command

**Comment by nivaca** [comment]
@alvinwan Thanks! I'm very happy with this package. I'm working with a set of XML TEI documents, which I translate into LaTeX using XSLT, but there is a lot of cleanup that must be done. With TeXSoup, I can do the cleanup in each of the elements, something which I couldn't do with plain RE.

**Comment by alvinwan** [comment]
@nivaca Woohoo, glad to hear it! 🎉

I'll go ahead and close this, but feel free to open a new issue if you have more questions.
