### ISSUE TITLE
URL encoded spaces cause "Malformed argument" Type error

### ISSUE THREAD

**Issue by NotQuiteLinus** [alvinwan/TexSoup#11]
Hi. 
I ran into an issue where a URL encoded space causes an error when initialising a TexSoup object:

TypeError: ('Malformed argument. First and last elements must match a valid argument format:', [...])

Sample latex:

```
\usepackage{hyperref}
\begin{itemize}
	\item \href{http://www.google.com}{Works OK}
	\item \href{http://www.google.com/Space%20Problem.aspx}{Not working}
\end{itemize}
```

Escaping the "%" to "\\%" works around it but I wondered if it's a bug or a general latex issue?

Thanks for the great library BTW!

**Comment by alvinwan** [comment]
Thanks @NotQuiteLinus ! This is actually a LaTeX quirk, since `%` is a comment. This means that everything starting from `20Pro...` is a comment, and `\href{...` is never closed. With that said, I should add a more informative error...
