### ISSUE TITLE
skip_envs is not working?

### ISSUE THREAD

**Issue by pablo-angulo** [alvinwan/TexSoup#120]
The optional argument `skip_envs` is not working if any environment that should be skipped is nested within any other environment (like `\begin{document}... \end{document})`.
Should be easy to fix, seems that inside `reader.read_expr` there is a nested call to read_env (`reader.py`: line 112)
```
            if expr.name in skip_envs:  
                read_skip_env(src, expr)
            else:
                read_env(src, expr, tolerance=tolerance, mode=mode)
```

which calls `read_expr` (`reader.py`: line 284), but the optional variable `skip_envs` is lost in the process, and takes on its default value `skip_envs=()`:
```
    contents = []
    while src.hasNext():
        if src.peek().category == TC.Escape:
            name, args = make_read_peek(read_command)(
                src, 1, skip=1, tolerance=tolerance, mode=mode)
            if name == 'end':
                break
        contents.append(read_expr(src, tolerance=tolerance, mode=mode))

```
Am I wrong?

**Comment by bpiwowar** [comment]
Stumbled upon the same problem - and installing from Pablo's git works perfectly. What is left to do since there is a pull request? Can I help?

**Comment by pablo-angulo** [comment]
Mi pull request has code that solves that problem, but also a commit for something else, because I forgot to open a branch for that first commit alone... (-_-)
So it would be cleaner to reject that pull request and open a new one with only the code relevant to this issue. You are welcome to do that! I will do it if you can't for any reason.
Regards

**Comment by bpiwowar** [comment]
OK, just cherry-picked and test on my use case that it effectively fixes the bug, and it does. I opened a pull request #128.
