### ISSUE TITLE
Unable to parse unmatched parenthesis in MATH context

### ISSUE THREAD

**Issue by muriloime** [alvinwan/TexSoup#126]
HI, congrats on the great package! 

I stumbled across a simple issue today. Unmatched parenthesis such as 

`data = """
 \begin{document}
 \section{Hello \textit{world}.}
 \subsection{Watermelon}
 $ x \in [0,\infty) $
 \end{document}
"""

soup = TexSoup(data)`

cause an error `"$" env expecting $. Reached end of file.`. 

I guess it must be relatively easy to change this.  

cheers

**Comment by ivanistheone** [comment]
I ran into this too https://github.com/alvinwan/TexSoup/issues/115 

If you want to fix this locally, you can add `'cup': (0, 0),` to SIGNATURES:
https://github.com/alvinwan/TexSoup/blob/master/TexSoup/reader.py#L29-L36

Another option would be to change  `$ x \in [0,\infty) $`  to `$ x \in$ $[0,\infty) $` until the long term fix lands
