### ISSUE TITLE
Duplicate tokens in parsed tabular

### ISSUE THREAD

**Issue by JohRausch** [alvinwan/TexSoup#17]
Hi Alvin, 
Thanks for sharing this cool project!

I'd like to parse a tabular environment and analyze rows and row elements separately after tokenizing it.
I'm interested in the global position of elements in the rows. Converting the whole tabular to a string and splitting by '\\\\' seems less appealing, because I won't be able to access the 'position' attribute anymore. 

I noticed that, when tokenizing this tabular, several tokens seem to be duplicated:

```
test_tabular = """\\begin{tabular}{cccc}               
\\hline
$E_{\\gamma}$ &
\\hspace{-2mm}$\\sigma(\\gpppizomega)$\\hspace{-2mm} &
\\hspace{-2mm}$\\sigma(\\gpppizomega)$\\hspace{-2mm}&
\\hspace{-2mm}$\\sigma(\\gpdeltaomega)$\\hspace{-2mm}\\\\  
ab & cd & ef & g\\\\                                       
\\hline
\\end{tabular}
"""

soup = TexSoup(test_tabular)                           
tabular = soup.tabular                                 
tabular_tokens = tabular.tokens                        

for token in tabular_tokens:                           
    print(token)
```
 

Output:

```
\hline $E_{\gamma}$
&
 &

\hspace{-2mm} $\sigma(\gpppizomega)$
\hspace{-2mm}
&
 &

\hspace{-2mm} $\sigma(\gpppizomega)$
\hspace{-2mm}
&
&

\hspace{-2mm} $\sigma(\gpdeltaomega)$
\hspace{-2mm}
\\
ab
&
cd
&
ef
&
g\\
\\
ab & cd & ef & g\\

\hline
```

- First tabular row:
    - The '&' symbols were duplicated. Some tokens are complete tabular cell contents, others only contain part of the cell content.
- Second row:
    - The row end '\\\\' was duplicated.
    - An additional token containing the complete second row was created in addition to the tokens with individual cell contents.

I'd be also grateful, if you could point me in a potentially better direction on how to robustly retrieve tabular rows and the contents of individual cells.

Thanks!

**Comment by alvinwan** [comment]
Thanks! This may have to do with the new `TextWithPosition` object. I'll check it out and get back to you. For now, `list(tabular.contents)` may work:
```
>>> list(tabular.contents)
[\hline $E_{\gamma}$, ' &\n', \hspace{-2mm} $\sigma(\gpppizomega)$, \hspace{-2mm}, ' &\n', \hspace{-2mm} $\sigma(\gpppizomega)$, \hspace{-2mm}, '&\n', \hspace{-2mm} $\sigma(\gpdeltaomega)$, \hspace{-2mm}, '\\\\  \nab & cd & ef & g\\\\                                       \n', \hline]
```

**Comment by JohRausch** [comment]
Thanks for help!
Regarding issue 2) with the duplicated token:
I think the problem is caused by following code in TexSoup/data.py, line 237:
```
for content in self.contents:
    if isinstance(content, TokenWithPosition):
        for word in content.split():
            yield word
    yield content
```
Changing it to 
```
for content in self.contents:
    if isinstance(content, TokenWithPosition):
        for word in content.split():
            yield word
    else:
        yield content
```
fixed it for me.

There were some other things I noticed. 
My understanding is that comments should be filtered out by TexSoup.
Reading a .tex file with following contents: 
```
%\begin{tabular}{cccc}
ab & cd & ef & g\\
%\end{tabular}
```
with
```
with open(filepath, 'r', encoding='utf-8') as f:
    data = f.read()
soup = TexSoup(data)
tokens = soup.tokens
for token in tokens:
    print('token: {}'.format(token))
```
still produces tokens of the commented passages:
```
token: %\begin{tabular}{cccc}                       
token: ab                                           
token: &                                            
token: cd                                           
token: &                                            
token: ef                                           
token: &                                            
token: g\\                                          
token: %                                            
token: \end{tabular} 
```

**Comment by alvinwan** [comment]
Thanks for the proposed fix; added it in! Mm, I believe the LaTeX there isn't valid:

```
%\begin{tabular}{cccc}
ab & cd & ef & g\\
%\end{tabular}
```
There should be a `%` for the middle row for it to work. With that said, I think keeping comments may be desirable. I could see a special annotation for comments being useful, but it seems like BeautifulSoup leaves comments in as well. Not sure about the design decision there, but sounds like it may be intentional. What are thoughts?

For now, I'll close this issue, as the original problem was fixed. Feel free to start a new issue for LaTeX comments.
