### ISSUE TITLE
Braces mistaken for command arguments, order not preserved

### ISSUE THREAD

**Issue by kaya3** [alvinwan/TexSoup#19]
When a string like r"\item aaa {\bbb} ccc" is parsed, the {\bbb} is mistaken for an argument of the \item command, and the resulting TexSoup object's contents are [r"\item{\bbb} aaa", "ccc"]. There appears to be no way to recover the original order from the resulting object.

**Comment by alvinwan** [comment]
Thanks for reporting! I refactored parts of the parser 42f7383 in addressing #21 and looks like this is fixed now
