### ISSUE TITLE
Math delimiters still tokenized in verbatim environments

### ISSUE THREAD

**Issue by kaya3** [alvinwan/TexSoup#22]
Since tokenization occurs before parsing, and the $ and $$ delimiters affect tokenization, the verbatim and lstlisting environments (which have special parsing rules) cannot handle unmatched math delimiters.

For example, `\begin{verbatim} $ \end{verbatim}` fails to parse.

**Comment by alvinwan** [comment]
Thanks for reporting! I squished the math env tokenization into the parser.

Test: https://github.com/alvinwan/TexSoup/blob/master/tests/test_parser.py#L182
