### ISSUE TITLE
TexSoup is incompatible with Python 2.7.x

### ISSUE THREAD

**Issue by philipaxer** [alvinwan/TexSoup#23]
Hi,

as the titel says, TexSoup does not work with Python 2.7.x

regards
Philip

**Comment by alvinwan** [comment]
Hey,

Thanks for the reporting this. I intentionally decided to drop support for Python 2.7.x, I would recommend using a virtual environment through pip or conda instead. With that said, I would welcome PRs that add Python2.7 support.

*I made a note in the README.
