### ISSUE TITLE
Incorrect handling of equation*

### ISSUE THREAD

**Issue by prabhuramachandran** [alvinwan/TexSoup#24]
This used to work with 0.1 and is broken in 0.1.1.

```
from TexSoup import TexSoup
s = TexSoup(r'''
\begin{equation*}
\beta = \gamma
\end{equation*}
''')
print(s)
```
The `=` sign is eaten up and it produces this:
```
\begin{equation*}\beta
\gamma\end{equation*}
```

**Comment by alvinwan** [comment]
Thanks for reporting! I added `equation*`, `align`, `align*` to the list of "ignore" environments. The problem was actually much deeper however, with how I parsed command arguments. Pushing patch now.
