### ISSUE TITLE
Strange errors with v0.1.1

### ISSUE THREAD

**Issue by prabhuramachandran** [alvinwan/TexSoup#25]
Again a change in 0.1.1:

```
from TexSoup import TexSoup
s = TexSoup(r'''
\frametitle{\emph{emph} $\alpha$}
''')
```
This converts very differently from before and seems to not be correct.

**Comment by alvinwan** [comment]
It looks like a43fd36 fixes the weird bugs. Feel free to re-open if otherwise. Unable to reproduce errors locally after a43fd36 though.

**Comment by prabhuramachandran** [comment]
This one is gone but there are others.

**Comment by alvinwan** [comment]
Thanks for letting me know. Mm, do you have a file or source that exhibits a bunch of these errors? The tests pass so the core functionality should be intact. I probably don't have enough tests.

**Comment by prabhuramachandran** [comment]
I am getting these from my tests in tex2ipy.  If it is not a bother, you could install that and see, the tests will not be too easy to debug for you though...

**Comment by alvinwan** [comment]
Mm I see. Ran the tests locally, I can try to thumb through these tests.
