### ISSUE TITLE
Handling verbatim and listings properly

### ISSUE THREAD

**Issue by prabhuramachandran** [alvinwan/TexSoup#3]
Thanks for the very handy package!  I noticed that the contents of verbatim and lstlistings environments is not handled carefully, leading to problems.

**Comment by alvinwan** [comment]
@prabhuramachandran Thank you for filing these bugs! Sorry for the late response. Will get to them as soon as my midterms are over. :P

**Comment by prabhuramachandran** [comment]
@alvinwan -- thank you, I have been using TexSoup in https://github.com/prabhuramachandran/tex2ipy  and just filed the issues that I ran into.
