### ISSUE TITLE
Items with labels

### ISSUE THREAD

**Issue by j-silver** [alvinwan/TexSoup#32]
Amended: actually square brackets must follow \item without whitespace to trigger the error ("AttributeError: 'str' object has no attribute 'text'")

Items can have labels within square parentheses:

\item[something here] some text

However this gives an error (sorry I can't copy and paste the code from mobile, however it is sufficient to create a TexSoup from a basic, one-item itemize environment to reproduce the error).

**Comment by alvinwan** [comment]
@j-silver Thanks for reporting, I totally forgot this is a possible scenario.

Thanks to @threecgreen we've got a fix (and a test to prove it)

Really appreciate both of you guys working on/using TexSoup
