### ISSUE TITLE
Unexpected EOFError

### ISSUE THREAD

**Issue by saeidnp** [alvinwan/TexSoup#36]
In some cases, the tokenizer fails to find the tokens correctly which in turn causes the program to break with an EOFError exception.
The following code is a sample for re-generating the error:
```
\begin{document}
\emph{2}\%
\end{document}
```

I monitored the tokens. The problem is that `\` after `\emph{2}` is considered as a command token and consequently, other tokenizer functions fail to tokenize `%` since it has a `\` before it.

**Comment by alvinwan** [comment]
@saeidnp Thanks for reporting. Hm, I can confirm TexSoup breaks--this is a tricky one.

I haven't taken a closer look yet, but strange https://github.com/alvinwan/TexSoup/blob/master/TexSoup/reader.py#L143 (`tokenize_line_comment`) didn't catch it. I suspect the logic belongs not in the tokenizer but in the command parser after tokenization https://github.com/alvinwan/TexSoup/blob/master/TexSoup/reader.py#L229 e.g., character that immediately follows is not a letter.

Then, there are weird cases like https://texfaq.org/FAQ-linmacnames, but I'll ignore that for now. I'll circle back in a bit, after giving it some thought.

**Comment by SimonMaenaut** [comment]
Seems #41 might fix this issue.

```
simon@zap:~/TexSoup$ python3.6
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from TexSoup import TexSoup
>>> t = TexSoup("""\\begin{document}
... \\emph{2}\%
... \\end{document}""")
>>> t.document
\begin{document}
\emph{2}\%
\end{document}
>>> list(t.document.contents)
[\emph{2}, \%]
>>> list(t.document.contents)[0]
\emph{2}
>>> type(list(t.document.contents)[0])
<class 'TexSoup.data.TexNode'>
>>> list(t.document.contents)[1]
\%
>>> type(list(t.document.contents)[1])
<class 'TexSoup.data.TexNode'>
>>> list(t.document.contents)[1].expr
TexCmd('%')
>>> exit()
simon@zap:~/TexSoup$ 
```
