### ISSUE TITLE
Issue with \item

### ISSUE THREAD

**Issue by saeidnp** [alvinwan/TexSoup#39]
There is a small issue in parsing "\item"s. If there is no argument and also no whitespace right after \item (e.g. a command, a label, a math environment with $), it breaks.
Here is an example that is one of the provided examples on this repo with a small change: I added a \label right after an \item.
Based on what I figured out so far, the core of the problem is forward_until function. if the criterion is true on the first token, it returns an empty string rather than a TokenWithPosition

```
\documentclass[a4paper]{article}

\begin{document}

\section{Chikin Tales}

\subsection{Chikin Fly}

Chickens don't fly. They do only the following:

\begin{itemize}
\item\label{some-label} waddle
\item plop
\end{itemize}

\section{Chikin Scream}

\subsection{Plopping}

Plopping involves three steps:

\begin{enumerate}
\item squawk
\item plop
\item repeat, unless ordered to squat
\end{enumerate}

\subsection{I Scream}

\end{document}
```

**Comment by alvinwan** [comment]
@saeidnp Wow, impressive - you hit the nail on its head. Fixing that `forward_until` function did the trick. Just pushed to master, and I'll include that in the next release!
