### ISSUE TITLE
Issue with inline math inside an item

### ISSUE THREAD

**Issue by prabhuramachandran** [alvinwan/TexSoup#4]
The following is not parsed properly:

```
\begin{itemize} 
\item This $e^{i\pi} = -1$ 
\end{itemize}
```

The `i\pi` is associated with the item.

**Comment by alvinwan** [comment]
@prabhuramachandran Thanks again for reporting this! Apologies for the late response - do let me know if anything else comes to mind. Summer will likely be less busy than the academic year.
