### ISSUE TITLE
Can't edit a string/content of a node

### ISSUE THREAD

**Issue by slkh** [alvinwan/TexSoup#46]
Thanks for this tool!

However, I'm not able to change the contents of a specific node, \cite for example.
I can see all the cites that are in the documents and I can view the contents using cite.string
But when I try to change the value (cite.string = 'xxx:2010') it does not allow me and gives me the following error 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: can't set attribute
```

Am I missing something or the tool simply does not allow it?

**Comment by SimonMaenaut** [comment]
As is, this tool does not allow you to set a string property, as a setter has not been implemented.
[Most properties are implemented in a similar ways and thus lack the ability to be changed.]
[More information about properties can be found in the [Python documentation](https://docs.python.org/3/library/functions.html#property).]
```
    @property
    def string(self):
        """Returns 'string' content, which is valid if and only if (1) the
        expression is a TexCmd and (2) the command has only one argument.
        """
        if isinstance(self.expr, TexCmd) and len(self.expr.args) == 1:
            return str(self.expr.args[0])
```
However there is an alternative way to set the value of a node.
```
simon@zap:~/TexSoup$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import TexSoup
>>> tex = TexSoup.TexSoup(r"""\cite{one:2018}""")
>>> tex.cite
\cite{one:2018}
>>> tex.cite.replace(TexSoup.TexSoup(r"""\cite{two:2018}""").cite)
>>> tex.cite
\cite{two:2018}
>>> exit()
```
This method is rather inefficient, and the idea of editing certain properties of a node directly is definitely something to consider as a possible future feature.

**Comment by alvinwan** [comment]
Thanks for reporting @slkh and responding @SimonMaenaut ! I'll leave this open as a feature request for setters. You make a good point it's inefficient to use `.replace(...)`.
