### ISSUE TITLE
Iterating over tokens throws an error

### ISSUE THREAD

**Issue by alcrene** [alvinwan/TexSoup#5]
The following code

    from TexSoup import TexSoup
    soup = TexSoup("""\\textbf{'Hello'}\\textit{'Y'}O\\textit{'U'}""")
    list(soup.tokens)

throws this error:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/alex/.local/lib/python3.4/site-packages/TexSoup/data.py", line 215, in tokens
        if isinstance(str, content):
    TypeError: isinstance() arg 2 must be a type or tuple of types

Python version 3.4.5 on linux

**Comment by alvinwan** [comment]
Oh my, that seems like a particularly bad bug. Let me take a look.

**Comment by duxan** [comment]
Hi, this points to simple syntax error in line 215. It should be `if isinstance(content, str):`
