### ISSUE TITLE
Malformed on arxiv papers

### ISSUE THREAD

**Issue by caseybasichis** [alvinwan/TexSoup#50]
Hi,

I'm getting errors loading most arxiv papers I've tried.  Maybe something I'm doing?
...
File "/home/caseybasichis/.local/lib/python3.6/site-packages/TexSoup/reader.py", line 348, in read_arg
    return Arg.parse(content)
  File "/home/caseybasichis/.local/lib/python3.6/site-packages/TexSoup/data.py", line 431, in parse
    ' mistyped closing punctuation, misalignment.' % (str(s)))
TypeError: Malformed argument. First and last elements must match a valid argument format....

...

'\\end', RArg('document')].
Common issues include: Unescaped special characters, mistyped closing punctuation, misalignment.

**Comment by alvinwan** [comment]
Thanks for reporting @caseybasichis . Do you have an isolated example of where TexSoup fails? I will close this for now, but please feel free to re-open. I know arxiv latex must be valid and compilable, but there are number of other common latex idioms (e.g., \def) that should affect TexSoup parsing but don't currently.
