### ISSUE TITLE
Malformed argument on valid LaTeX, goes away after inserting whitespace

### ISSUE THREAD

**Issue by vluzko** [alvinwan/TexSoup#51]
On the input: 
    
    \[
        \textrm{supp} f = \overline{\{p \in M|f(p) \neq 0\}}
    \]
I get the error:

    TypeError: Malformed argument. First and last elements must match a valid argument format. In this case, TexSoup could not find matching punctuation for: ['{', TexCmd('', [RArg('p ', '\\in', ' M|f(p) ', '\\neq', ' 0\\}')]), '\n    \\]\n\n', '\n\n'].

Inserting a space after the overline fixes this:
    
    \[
        \textrm{supp} f = \overline{ \{p \in M|f(p) \neq 0\}}
    \]

**Comment by alvinwan** [comment]
Thanks for reporting @vluzko! Just pushed `0.1.4` to pypi, which fixes this:

```
>>> from TexSoup import TexSoup
>>> TexSoup("""\[
...     \textrm{supp} f = \overline{\{p \in M|f(p) \neq 0\}}
... \]""")
\[
    	extrm{supp} f = \overline{\{p \in M|f(p)
eq 0\}}
\]
```
