### ISSUE TITLE
I cant load this file.

### ISSUE THREAD

**Issue by Bobrov1437** [alvinwan/TexSoup#52]
When I try to process files, I get an error: TypeError: ('Malformed argument. First and last elements must match a valid argument format:', ['{', TexCmd('frac', [RArg('2'), RArg('\\left(\\', 'gamma-1', '\\right)}')]), ' (r, ', TexCmd('varphi,z'), '\\left(u', '^2', '\\left(r', ',', TexCmd('varphi,z'), '\\right)+', 'v^2', '\\left(r', ',', TexCmd('varphi,z'), '\\right)+', 'w^2', '\\left(r', ',', TexCmd('varphi,z'), '\\right)\\', 'right)rdr', '\\right]d', TexCmd('varphi'), '\\right\\}', 'dz,\n', ...

This file: https://drive.google.com/open?id=1fwm5zpzJetNm8MorjPQ34ySsSFoVRCxM

**Comment by alvinwan** [comment]
Hello @Bobrov1437 . I'm assuming you mean it failed on the latex for that PDF. Do you have an isolated example of where TexSoup fails? Meaning a latex snippet, no more than a few lines, that reproduces the error. I will close this for now, but please feel free to re-open.
