### ISSUE TITLE
$ and $$ math is not parsed

### ISSUE THREAD

**Issue by akhmerov** [alvinwan/TexSoup#7]
To reproduce:
```python
In [4]: list(TexSoup.read('$\lambda$').children)
Out[4]: [TexCmd('lambda$')]
```
Expected:
`$` and `$$` should be treated as paired delimiters and result in a correct environment.
TexSoup version:
0.0.3

**Comment by akhmerov** [comment]
Of course, this is unless they are escaped.

**Comment by alvinwan** [comment]
Thanks! Just fixed it with #8 .

```
>>> from TexSoup import TexSoup
>>> soup = TexSoup('$\lambda$')
>>> contents = list(soup.contents)
>>> contents
[$\lambda$]
>>> env = contents[0]
>>> env.name
'$'
>>> list(env.contents)
['\\lambda']
```

**Comment by akhmerov** [comment]
Thanks a lot!

I see two problems so far:
1. `TeXSoup('$ \$ $')` raises a type error.
2. Under some condition `soup.find_all('$')` returns nothing, but I'm not yet sure under which conditions this happens, trying to pin it down.

**Comment by akhmerov** [comment]
I think I found two more quirks:
```python
print(TexSoup.TexSoup(r'\begin{a} \end{a}$ b$').find('a'))
print(TexSoup.TexSoup(r'\begin{a} $ b$ \end{a}').find('$'))
```

**Comment by alvinwan** [comment]
@akhmerov oh wow, thanks, I'll check it out.
