### ISSUE TITLE
Getting to the tree structure

### ISSUE THREAD

**Issue by colespeck** [alvinwan/TexSoup#72]
Hi, I am trying to take the latex file, and have it formatted into the tree structure. For instance with the chikin.tex , I would have document height = 0 the sections at height = 1,  the two subsections at height =2 and then at height =3 have a list/ itemize for each subsection. So I want this as labels for each section, subsection, and itemizers, as well as have the text that go along with them, not just the titles that are associated with things like sections. With this is mind, can I still have the natural ordering of the sections from the original document? I am assuming yes because if we can make the tree, we can do a Depth First Search of the tree. Is this possible with the tools provided, or will this take rewriting the classes provided?

**Comment by alvinwan** [comment]
Absolutely, this is possible. I've also released a rudimentary implementation of this at https://github.com/alvinwan/tex2py. dfs (preorder) indeed recovers the original document structure.

**Comment by colespeck** [comment]
So I have been doing a DFS by just iterating over the documents root node. I have a problem though in that I want to capture that a element is a section, a environment like tabular, and then the corresponding text with it. I basically had to hack together what I have now because the actual search look like this
[TexSoup parse tree.pptx](https://github.com/alvinwan/TexSoup/files/3345909/TexSoup.parse.tree.pptx)
This is by calling .descendants() on the root node.
