### ISSUE TITLE
Parse error when a group is after a command with argument

### ISSUE THREAD

**Issue by peterzjx** [alvinwan/TexSoup#73]
A minimum example is
`doc = TexSoup(r"\label{123} {\it 123}")`
calling `doc.label` gets `\label{123}{\it 123}`.

It also happens inside a table environment with `\caption{}`

**Comment by alvinwan** [comment]
@peterzjx Thanks for reporting -- a contributor in the community has since fixed this #87

**Comment by alvinwan** [comment]
It looks like this is also related to #59 , where TexSoup needs awareness of command-specific expectations (e.g., that `label` only takes in one required argument) Otherwise, it seems impossible for TexSoup to know whether or not to associate the required argument with the previous command.

**Comment by alvinwan** [comment]
*Closing this issue, because as of v0.2.1, there is no longer a parse error. However, it's worth mentioning that TexSoup still incorrectly associates the group with the previous command, as though it were a command argument. Will address in response to #59.
