### ISSUE TITLE
Options for parsing with fault tolerance or error recovery?

### ISSUE THREAD

**Issue by andrewhead** [alvinwan/TexSoup#77]
Hi there, @alvinwan and TexSoup community! Thanks for this tool, it has been fun to use a lightweight and clean Python interface for parsing TeX.

Like #50, I'm parsing pretty complex TeX documents and see a variety errors for different files. The ideal behavior of TexSoup in my case is if it returned a partial tree even if it encounters a failure. For example, if it's expecting `\end{environment}` and doesn't see one, maybe it returns the "soup" of everything it's seen so far and skips the rest. Or maybe it inserts the expected `\end` command, like TeX engines usually do.

Is there some option to turn on fault tolerance like this, in this project or in [tex2py](https://github.com/alvinwan/tex2py)? If not, where would you recommend I extend TexSoup's code to introduce such fault tolerance? And if I or someone implemented a feature like that, would this be something that would be considered pull request-worthy?

Thanks again for a useful tool, and cheers :)

**Comment by alvinwan** [comment]
@andrewhead That's interesting. The best-effort response would likely have to handle these aberrations gracefully, instead of returning a partial parse tree. For example, if the parser receives a flag that indicates best-effort guessing, the following function could simply wrap up the un-closed environment instead of giving up: https://github.com/alvinwan/TexSoup/blob/master/TexSoup/reader.py#L358

There are some edge cases to consider though -- for example, how would best-effort work for the following?

```
\begin{enva}
\begin{envb}
\end{enva}
\end{envb}
```

**Comment by andrewhead** [comment]
@alvinwan agreed, graceful handling of aberrations could be really useful 👍 

You make a good point too. In your `enva`, `envb` example, TeX has some really weird semantics for how it tries or doesn't try to close environments. It would probably require an reimplementation of the TeX engine to handle them all XD. Though for my purposes, I think even this output could be useful:

```
- begin{enva}
|-- begin{envb}
|-- *_force_* end{envb}
- end{enva}
- *_ignore* end{envb}
```

When I use BeautifulSoup with a fault-tolerant parser, I usually assume the tree won't be quite right in some places if the source was malformed, that's just the couple of 🥚s I gotta crack to make the souffle. While I can't speak for other TexSoup users, I imagine  I'd appropriately set expectations if I was using TexSoup in an error-tolerant mode.

**Comment by alvinwan** [comment]
Just added `tolerance` kwarg to the `TexSoup` function to support exactly the above possibility, where environments are unclosed.

[Sample usage](https://github.com/alvinwan/TexSoup/blob/0faf0dcd8e041ce6ce6ca7294d166beba849de87/tests/test_parser.py#L545)

```
soup = TexSoup(r"""
    \begin{enva}
    \begin{envb}
    \end{enva}
    \end{envb}""", tolerance=1)
```

*Docs and tolerance of other errors coming soon...
