### ISSUE TITLE
It dose not parse env with comments

### ISSUE THREAD

**Issue by Freakwill** [alvinwan/TexSoup#81]
I just add % in the align env, then I got error of EOFError: Expecting \end{align*}. Reached end of file.

 \begin{align*}
    (\intm{|K|^p}{|x|>R}{x})^{\inv{p}}&\leq&\normx{K}{p}\\% 
    &\leq&\normx{K}{W^\alpha(L^q,\ell^{s+n\alpha(\inv{p}-\inv{q}),1})}.
  \end{align*}

**Comment by alvinwan** [comment]
@Freakwill Thank you for reporting! Hm, I was unable to reproduce on either the `master` branch or the latest version of `TexSoup` (0.0.2). Please feel to open if this problem persists. The following code appears to work without a hitch, however.

```
>>> soup = TexSoup(r"""\begin{align*}
... (\intm{|K|^p}{|x|>R}{x})^{\inv{p}}&\leq&\normx{K}{p}%
... &\leq&\normx{K}{W^\alpha(L^q,\ell^{s+n\alpha(\inv{p}-\inv{q}),1})}.
... \end{align*}""")
>>> soup = TexSoup(r"""\begin{align*}
... (\intm{|K|^p}{|x|>R}{x})^{\inv{p}}&\leq&\normx{K}{p}\%
... &\leq&\normx{K}{W^\alpha(L^q,\ell^{s+n\alpha(\inv{p}-\inv{q}),1})}.
... \end{align*}""")
```
