### ISSUE TITLE
Can not delete TokenWithPosition objects

### ISSUE THREAD

**Issue by mawebi** [alvinwan/TexSoup#82]
Hi.
I'm trying to delete a whole section or environment. But it is only possible to delete TexExpr objects and the TokenWithPosition objects can not be deleted.
Minimal example:
```
    tex = """Test    
    \section{Hallo}
    Delete me
    \section{Hallo}
    """
    soup = TexSoup(tex)
    for node in soup.all:
        if "Delete me" in node:
            node.delete()
    print(soup)
```
Ouput:
```
Traceback (most recent call last):
[...]
/TexSoup/utils.py", line 61, in __getattr__
    return getattr(self.text, name)
AttributeError: 'str' object has no attribute 'delete'

Process finished with exit code 1
```

This behaviour seams to be not necessary. I added a delete function to the TokenWithPosition class (and a parent variable) and had to change all function in the data.py, where the parent object is initalized. But now it works as intended.

Is there a easy solution for this?

More Background information, what I would like to achieve:
Change the TexSoup
FROM
```
\section{One}
Text
\section{Two}
Text
```
TO
```
\section{Changed}
Changed
\section{Two}
Text
```
Therefore I wrote a function to extract the section one, now I would like to delete it (here is my problem), and than insert a new one.

**Comment by alvinwan** [comment]
@mawebi Thanks for reporting! I ended up adding a new `TexExpr` (`TexText`) that is added to the parse tree. Now, the above loop over the soup, deleting text, will work:

```
    tex = """Test    
    \section{Hallo}
    Delete me
    \section{Hallo}
    """
    soup = TexSoup(tex)
    for node in soup.all:
        if "Delete me" in node:
            node.delete()
    print(soup)
```
