### ISSUE TITLE
TextEnv name change do not update the node, nor the parent

### ISSUE THREAD

**Issue by hanzckernel** [alvinwan/TexSoup#94]
Overwriting the name property of `TexEnv` or `TexNode` object does not update its environment nor the content of its parent node.

For instance:
```python
soup = TexSoup('''
\\begin{theorem}
\\begin{equation}
t = s
\\end{equation}
\\end{theorem}
'''

eqn = soup.find('equation')
eqn.name = 'eqn'
print(eqn, eqn.parent)
```
still gives:
```latex
\begin{equation}
        t = s
\end{equation} 

\begin{theorem}
   \begin{equation}
        t = s
    \end{equation}
\end{theorem}
```
whereas the expected output (as in bs4) should change `equation` environment to `eqn`.

**Comment by alvinwan** [comment]
Thanks for reporting @hanzckernel! I'll take a look at this. It looks like `TexSoup` has similar issues with other attributes.
